services:
- redis-server

language: python

python:
- "2.7"
- pypy-5.3.1

install:
- pip install -r requirements.txt
- pip install -e .
- pip install codeclimate-test-reporter
- pip install coverage
- make travis-install

script:
- make start
- nosetests -v --with-coverage --cover-tests 
- make stop

